### ISSUE TITLE
Error Boundary Text Overflow

### ISSUE THREAD

**Issue by zachintosh** [digital-taco/react-draft#28]
<img width="1014" alt="Screen Shot 2019-11-05 at 6 00 38 PM" src="https://user-images.githubusercontent.com/16728078/68259141-42d7fe00-fff6-11e9-8f7c-6f8598af7720.png">

**Comment by kyle-west** [comment]
This is caused by `white-space: pre;` it needs to be `white-space: pre-wrap;`

**Comment by kyle-west** [comment]
Fixed in https://github.com/digital-taco/react-draft/commit/310c1e399007f59519df09e50b42aca5ab89f428
